### PR TITLE
Add option to pass style to dialogpreference

### PR DESCRIPTION
**Pull request by DerTyp7214**

### CODE REVIEW

**Comment by DerTyp7214** [comment]
ok, i figured out while doing this that using MaterialAlertDialog fixed my problem

i am sorry for this "commit spam"

**Comment by Maxr1998** [comment]
I'm not sure that this change warrants adding another library - especially since it isn't an exactly small artifact either. Preferably, people should be able to override the builder to supply it themselves, maybe through a factory lambda on the DialogPreference.
The problem here is still maintaining backwards compatibility.

**Comment by DerTyp7214** [comment]
Yeah, this would be a better solution

**Comment by msfjarvis** [comment]
Is there a planned resolution for this yet? It's become a bigger problem now with Material You more or less mandating the use of `MaterialAlertDialogBuilder` in apps to leverage the new design system fully. I'm happy to contribute code if there's consensus on how to approach this.

**Comment by Maxr1998** [comment]
Not yet, but I can look into this today or on the weekend. I already did some experimenting a few months ago, but I haven't gotten around to finishing it yet.

**Comment by Maxr1998** [comment]
@msfjarvis does this (3ff76d7afc6d33cf6847c577004d4e9f1d74489a) work for you?

**Comment by msfjarvis** [comment]
> @msfjarvis does this (3ff76d7afc6d33cf6847c577004d4e9f1d74489a) work for you?
> If so, I'll push a new release very soon.

It's perfect, thank you so much!

**Comment by Maxr1998** [comment]
Released as 2.2.0, should be available on MavenCentral now. Let me know if there are any issues. Closing this PR now.

**Pull request closed without merging**
